spring.application.name=SistemaGestionDeProyectos

# PUERTO
server.port=8080

# LOCAL
spring.datasource.url= jdbc:mysql://localhost:3306/DB_SISTEMA_GESTION_PROYECTOS
spring.datasource.username= root
# spring.datasource.password

# MYSQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# Para ver la documentacion una vez levantada la aplicacion
# http://localhost:8080/swagger-ui.html

# Datos iniciales descomentar la primera vez que se ejecuta la aplicacion y luego volver a comentar para que no se sobreescriba la base de datos

# spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:data.sql
# spring.jpa.defer-datasource-initialization=true